close all
clear

% FOLDER PATH NAMES
regX_1 = 'Excel Sheets/5x5_regX_1.xlsx';
regX_2 = 'Excel Sheets/5x5_regX_2.xlsx';
regX_3 = 'Excel Sheets/5x5_regX_3.xlsx';
regY_1 = 'Excel Sheets/5x5_regY_1.xlsx';
regY_2 = 'Excel Sheets/5x5_regY_2.xlsx';
regY_3 = 'Excel Sheets/5x5_regY_3.xlsx';

regX = {regX_1, regX_2, regX_3};

% CONSTANTS
micNum = 3;

% SWITCHES
fileNames = regX;

numRowsPerFile = 10;
numFilesPerLabel = 10;
numForces = 3;
numFilesPerForce = 5;
labelNum = 10;
figDims = [3 3];

cmap = colormap('hsv');
close all % Close the figure that gets automatically generated by colormap command

% PROCESSING

% Create a separate figure for each microphone
for k = 1:micNum
    figure

    fileName = fileNames{k};
    micData = readmatrix(fileName);

    plotColors = zeros(labelNum, 3);

    % Prepare for custom legend
    for i = 1:labelNum
        plotColors(i,:) = cmap(round(i * height(cmap)/labelNum),:);
        hold on; plot(NaN, NaN, 'Color', plotColors(i,:), 'LineWidth', 2); % Invisible plots for legend
    end

    % Get all the files from a lable
    for i = 1:labelNum
        % Get all the pulses from a trial and plot their average
        for m = 1:numFilesPerLabel
            startInd = (i-1) * numFilesPerLabel * numRowsPerFile + (m-1) * numRowsPerFile + 1;
            endInd = startInd + numRowsPerFile - 1;

            dataBlock = micData(startInd:endInd,:);

            avgDataBlock = mean(dataBlock, 1);

            hold on
            g = plot(avgDataBlock);
            % Equi-distant colors drawn from the colormap
            g.Color = plotColors(i,:);
        end
    end

    ylim([50 110])

    legendStrings = "Distance = " + string(1:1:labelNum);
    legend(legendStrings)
end